// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoblPTu1IpTRCR3vGw4-DoT27kC8vV1OM',
    appId: '1:909367967285:web:bd6885210434e709fdbb7c',
    messagingSenderId: '909367967285',
    projectId: 'study-planner-a21e2',
    authDomain: 'study-planner-a21e2.firebaseapp.com',
    storageBucket: 'study-planner-a21e2.firebasestorage.app',
    measurementId: 'G-R240LJQ805',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGjkVx8Xp2cXDE370WeY2NnrlA1L6CqY',
    appId: '1:909367967285:android:2ddd96939e96b28bfdbb7c',
    messagingSenderId: '909367967285',
    projectId: 'study-planner-a21e2',
    storageBucket: 'study-planner-a21e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRWq6f5Pb2RChXn_vMSgunU3QdT5B81w',
    appId: '1:909367967285:ios:8e560351f7a0fe0efdbb7c',
    messagingSenderId: '909367967285',
    projectId: 'study-planner-a21e2',
    storageBucket: 'study-planner-a21e2.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJRWq6f5Pb2RChXn_vMSgunU3QdT5B81w',
    appId: '1:909367967285:ios:8e560351f7a0fe0efdbb7c',
    messagingSenderId: '909367967285',
    projectId: 'study-planner-a21e2',
    storageBucket: 'study-planner-a21e2.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoblPTu1IpTRCR3vGw4-DoT27kC8vV1OM',
    appId: '1:909367967285:web:0bcd7752ab8b7c93fdbb7c',
    messagingSenderId: '909367967285',
    projectId: 'study-planner-a21e2',
    authDomain: 'study-planner-a21e2.firebaseapp.com',
    storageBucket: 'study-planner-a21e2.firebasestorage.app',
    measurementId: 'G-X694ZKR3ZR',
  );
}
